### ISSUE TITLE
APIv1 deprecation

### ISSUE THREAD

**Issue by spawn-guy** [Notificare/notificare-php-push-api#1]
we've received an email about deprecation of APIv1 and we have a php backend that sends pushes through notificare.

i see that this repo was updated 7 years ago. does this repo support APIv2?

what SDK would you suggest to use with php?

**Comment by spawn-guy** [comment]
i've open-sourced my tiny implementation of `laravel-notificare` package for Laravel here https://github.com/spawn-guy/laravel-notificare 

but (i think) it is APIv1 only. so now i am considering or updating my implementation to APIv2 or, actually, implementing/generating a full notificare sdk based on `api-blueprint` (but this is problematic to a certain degree)

i've used `openapi-generator` for some of my `OpenAPIv3` specification to generate some SDKs, but i don't see this level of community/tool support for `api-blueprint`.

can you help converting your api-blueprint to a proper OAS3? do you have plans on supporting php-sdk in general and Laravel in particular?

shall we brainstorm?

**Comment by jjonthemix** [comment]
Hi Paul, 

This repo is a very old example code for the REST API endpoints which we do not actively work on it. 

The  email we sent out last week was related to the front-end SDKs, namely iOS, tvOS, Android and Web. Only for those libraries we are dropping support and urging developers to update to v2. 

When it comes to backend libraries, all our examples are not really complete or battle tested, and serve only for demo code or as an intro to our REST API. The REST API is version agnostic and all endpoints still reside in the same URL, push.notifica.re. You should take a look at our official documentation, which contains a OpenAPIv3 blueprint ready to be downloaded. This is visible here:

https://api-docs.notifica.re/

You are still relying on an old API Blueprint document that we no longer update, so please use the documentation in the URL above to refer to any or our REST APIs. 

We do not plan to support any backend library in general and instead we are putting our efforts in providing all the documentation necessary for developers to build upon our blueprints available at:

https://docs.notifica.re/api/

We appreciate your effort in developing that Laravel package and we will keep that in mind and forward clients to it if it ever comes up, although it is still using old endpoints. Basically when we introduced Email and SMS, last year, the push endpoints did move to a different path (although the old ones still work), as you can see here:

https://api-docs.notifica.re/#tag/Messages

Hope this helps.

Regards,
Joel Oliveira

**Comment by spawn-guy** [comment]
Awesome news. I thought that you are still on api-blueprint, didn't notice that new docs are based on oas3. 
I think I'll give a shot to oas3+generator + separate sdk package + laravel wrapper. 

And thank you for clarification of that APIv1. I was looking into differences and noticed only this push sub-path. And now it is clear that deprecation is for client libraries.
